### ISSUE TITLE
cant get it to work :(

### ISSUE THREAD

**Issue by fly2hi** [gibigo/cornix-tv-channel#54]
don't make fun of me 
i am not a programmer , just trying useful stuff
i reach to a point where i am able to open the script webpage 
but nothing after that
hopefully someone will help know how to change the host name aas its stuck on [ Base URL: https://yourforwarder.io/api/v1 ]
and what ever comes next :)
thanks

**Comment by jon4hz** [comment]
Unfortunately this project is currently everything else than user-friendly. 
It requires some basic knowledge on how to use a REST API in order to set it up. The swagger UI is automatically generated by a third party software and `https://yourforwarder.io/` is only a placeholder I put there because I don't host this project publicly at the moment. The swagger page is intended to give you an overview of the available endpoints but not to use it directly from there.
